:compat-mode:
= Lab 13 - Build a Product Recommendation Service with Neo4J

[abstract]
--
In this lab we'll begin the second subproject of our complete cloud-native application architecture: _SpringBox_, which implements the movie browsing portion of a ``Redbox-like'' website.
This microservice will provide the _Movie Recommendations Service_, which will allow us to create and browse reviews for movies.
We'll be using Neo4J to model the relationship between people and the movies that they like.
Neo4J provides a powerful graph query language called Cypher which will allow us to create a highly performant query that returns ``movies liked by people who liked the movie you're currently browsing.''

[graphviz, graph_diagram, png, align="center"]
....
digraph {
  rankdir=LR;
  node [shape = circle];
  "Person A" -> "Movie A" [ label = "Likes" ];
  "Person A" -> "Movie B" [ label = "Likes" ];
  "Person A" -> "Movie C" [ label = "Likes" ];
  "Person B" -> "Movie B" [ label = "Likes" ];
  "Person C" -> "Movie A" [ label = "Likes" ];
  "Person C" -> "Movie C" [ label = "Likes" ];
}
....

We're still using the http://grouplens.org/datasets/movielens/[MovieLens] dataset, and here we'll link back to movies in the dataset by their `mlId` or ``MovieLens ID.''

This project comes with vendored source for a Spring Cloud Connector for Neo4J, as that connector has not yet been released as part of the core project.
--

NOTE: The completed code for this lab can be found at `$COURSE_HOME/day_01/session_04/lab_13/complete/springbox-recommendations`.

== Developing the Service

. Change to the lab directory:
+
----
$ cd $COURSE_HOME/day_01/session_04/lab_13/initial/springbox-recommendations
----
+
and import the project (via `pom.xml`) into your IDE of choice.

. Create the package `io.springbox.recommendations.domain` and in that package create the class `Movie`. Into that file you can paste the following source code:
+
----
@NodeEntity
public class Movie {

    @GraphId
    private Long id;

    @Override
    public String toString() {
        return "Movie{" +
                "id=" + id +
                ", mlId='" + mlId + '\'' +
                ", title='" + title + '\'' +
                '}';
    }

    @Indexed(unique = true)
    private String mlId;
    private String title;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMlId() {
        return mlId;
    }

    public void setMlId(String mlId) {
        this.mlId = mlId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
----

. Also in the package `io.springbox.recommendations.domain` create the class `Person`. Into that file you can paste the following source code:
+
----
@NodeEntity
public class Person {

    @GraphId
    private Long id;
    private String userName;
    private String firstName;
    private String lastName;

    @Override
    public String toString() {
        return "Person{" +
                "id=" + id +
                ", userName='" + userName + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                '}';
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}
----

. Also in the package `io.springbox.recommendations.domain` create the class `Likes`. Into that file you can paste the following source code:
+
----
@RelationshipEntity(type = "LIKES")
public class Likes {

    @GraphId
    private Long id;

    @StartNode
    private Person person;

    @EndNode
    private Movie movie;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public Movie getMovie() {
        return movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

    @Override
    public String toString() {
        return "Likes{" +
                "id=" + id +
                ", person=" + person +
                ", movie=" + movie +
                '}';
    }
}
----

. Create the package `io.springbox.recommendations.repositories` and in that package create the interface `MovieRepository`. Into that file you can paste the following source code:
+
----
public interface MovieRepository extends GraphRepository<Movie> {
    Movie findByMlId(String mlId);

    @Query("MATCH (p:Person) WHERE p.userName = {0} MATCH p-[:LIKES]->movie<-[:LIKES]-slm-[:LIKES]->recommendations " +
    "WHERE not(p = slm) and not (p--recommendations) return recommendations")
    Iterable<Movie> recommendedMoviesFor(String userName);

    @Query("MATCH (movie:Movie) WHERE movie.mlId = {0} MATCH movie<-[:LIKES]-slm-[:LIKES]->recommendations " +
    "RETURN distinct recommendations")
    Iterable<Movie> moviesLikedByPeopleWhoLiked(String mlId);
}
----

. Also in the package `io.springbox.recommendations.repositories` create the interface `PersonRepository`. Into that file you can paste the following source code:
+
----
public interface PersonRepository extends GraphRepository<Person> {
    Person findByUserName(String userName);
}
----

. Also in the package `io.springbox.recommendations.repositories` create the interface `LikesRepository`. Into that file you can paste the following source code:
+
----
public interface LikesRepository extends GraphRepository<Likes> {
}
----

. Create the package `io.springbox.recommendations.controllers` and in that package create the class `MovieController`. Into that file you can paste the following source code:
+
----
@RestController
public class MovieController {

    @Autowired
    MovieRepository movieRepository;

    @RequestMapping(value = "/movies", method = RequestMethod.GET)
    public Iterable<Movie> movies() {
        return movieRepository.findAll();
    }

    @RequestMapping(value = "/movies", method = RequestMethod.POST)
    public ResponseEntity<Movie> createMovie(@RequestBody Movie movie) {
        movieRepository.save(movie);
        return new ResponseEntity<>(movie, HttpStatus.CREATED);
    }
}
----

. Also in the package `io.springbox.recommendations.controllers` create the class `PersonController`. Into that file you can paste the following source code:
+
----
@RestController
public class PersonController {

    @Autowired
    PersonRepository personRepository;

    @RequestMapping(value = "/people", method = RequestMethod.GET)
    public Iterable<Person> people() {
        return personRepository.findAll();
    }

    @RequestMapping(value = "/people", method = RequestMethod.POST)
    public ResponseEntity<Person> createPerson(@RequestBody Person person) {
        personRepository.save(person);
        return new ResponseEntity<>(person, HttpStatus.CREATED);
    }

}
----

. Also in the package `io.springbox.recommendations.controllers` create the class `LikesController`. Into that file you can paste the following source code:
+
----
@RestController
public class LikesController {

    @Autowired
    LikesRepository likesRepository;

    @RequestMapping(value = "/likes", method = RequestMethod.GET)
    public Iterable<Likes> likes() {
        return likesRepository.findAll();
    }
}
----

. Also in the package `io.springbox.recommendations.controllers` create the class `RecommendationsController`. Into that file you can paste the following source code:
+
----
@RestController
public class RecommendationsController {

    @Autowired
    MovieRepository movieRepository;
    @Autowired
    PersonRepository personRepository;
    @Autowired
    LikesRepository likesRepository;

    @RequestMapping(value = "/recommendations/{userName}/likes/{mlId}", method = RequestMethod.POST)
    public ResponseEntity<Likes> createPersonMovieLink(@PathVariable String userName,
                                                       @PathVariable String mlId) {
        Person person = personRepository.findByUserName(userName);
        Movie movie = movieRepository.findByMlId(mlId);

        Likes likes = new Likes();
        likes.setPerson(person);
        likes.setMovie(movie);
        likesRepository.save(likes);

        return new ResponseEntity<>(likes, HttpStatus.CREATED);
    }

    @RequestMapping(value = "/recommendations/forUser/{userName}", method = RequestMethod.GET)
    public Iterable<Movie> recommendedMoviesForUser(@PathVariable String userName) {
        return movieRepository.recommendedMoviesFor(userName);
    }

    @RequestMapping(value = "/recommendations/forMovie/{mlId}", method = RequestMethod.GET)
    public Iterable<Movie> recommendedMoviesForMovie(@PathVariable String mlId) {
        return movieRepository.moviesLikedByPeopleWhoLiked(mlId);
    }
}
----

. Create the package `io.springbox.recommendations.config` and in that package create the class `Neo4jConfig`. Into that file you can paste the following source code:
+
----
@Configuration
public class Neo4jConfig extends Neo4jConfiguration {
    public Neo4jConfig() {
        setBasePackage("io.springbox.recommendations.domain");
    }
}
----

. Also in the package `io.springbox.recommendations.config` create the class `LocalConfig`. Into that file you can paste the following source code:
+
----
@Configuration
@Profile("default")
public class LocalConfig {

    @Bean
    public GraphDatabaseService graphDatabaseService() {
        return new SpringRestGraphDatabase("http://localhost:7474/db/data/");
    }

}
----

. Add the `@EnableNeo4jRepositories` annotation to `io.springbox.recommendations.SpringboxRecommendationsApplication`:
+
----
@SpringBootApplication
@EnableNeo4jRepositories(basePackages = "io.springbox.recommendations.repositories") // <--- Add this!
public class SpringboxRecommendationsApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringboxRecommendationsApplication.class, args);
    }
}
----

. Add the following to `application.properties` -- we'll eventually want to run multiple apps locally, so we need to change the port:
+
----
server.port=8082
----

. To run the application locally, you'll need a local Neo4J install.  You can alternatively skip running locally and avoid 
installing Neo4J on your machine.  If you choose to not run locally, skip to the Cloud Foundry section.  Otherwise, you need to download the Neo4J Community Edition (you must use version 2.1.x) http://neo4j.com/download/[here].  Also, turn off authentication in Neo4J in neo4j-server.properties (dbms.security.auth_enabled=false).

. Build the JAR:
+
----
$ mvn package
----

. Run the application:
+
----
$ java -jar target/springbox-recommendations-0.0.1-SNAPSHOT.jar
----

. Visit the Neo4J web admin console (http://localhost:7474/browser/). Run the following Cypher queries to load test data:
+
----
LOAD CSV WITH HEADERS FROM "https://raw.githubusercontent.com/mstine/CloudNativeArchitectureClass/citi/day_01/session_04/lab_13/movies.csv" AS row CREATE (movie:Movie:_Movie {mlId:row.mlId, title:row.title})

LOAD CSV WITH HEADERS FROM "https://raw.githubusercontent.com/mstine/CloudNativeArchitectureClass/citi/day_01/session_04/lab_13/people.csv" AS row CREATE (:person:Person:_Person {userName:row.userName, firstName:row.firstName, lastName:row.lastName})
----

. Access the application using `curl` to make sure everything is working properly:
+
----
$ curl -i localhost:8082/recommendations/forMovie/1
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Tue, 17 Feb 2015 06:02:10 GMT
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
X-Application-Context: application:8082

[
    {
        "id": 3079,
        "mlId": "2",
        "title": "GoldenEye (1995)"
    }
]
----

== Preparing for Cloud Foundry

. Create the neo4J service.

+
$ cf cs p-neo4j development springbox-recommendations-db
 

. In the package `io.springbox.recommendations.config` create the class `CloudConfig`. Into that file you can paste the following source code:
+
----
@Configuration
@Profile("cloud")
public class CloudConfig extends AbstractCloudConfig {

    @Bean
    GraphDatabaseService graphDatabaseService() {
        return connectionFactory().service(GraphDatabaseService.class);
    }
}
----

. Rebuild the JAR:
+
----
$ mvn package -DskipTests
----

== Deploying to Cloud Foundry

. Create an application manifest in `manifest.yml`:
+
[source,yml]
----
---
applications:
- name: springbox-recommendations
  host: springbox-recommendations-${random-word}
  memory: 512M
  instances: 1
  path: target/springbox-recommendations-0.0.1-SNAPSHOT.jar
  env:
    SPRING_PROFILES_ACTIVE: cloud
  services:
  - springbox-recommendations-db
----

. Push to Cloud Foundry:
+
----
$ cf push

...

Showing health and status for app springbox-recommendations in org oreilly-class / space instructor as mstine@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 512M x 1 instances
urls: springbox-recommendations-preadherent-werewolf.cfapps.io
last uploaded: Tue Feb 17 05:40:41 UTC 2015

     state     since                    cpu    memory           disk
#0   running   2015-02-16 09:41:31 PM   0.0%   366.7M of 512M   146.9M of 1G
----

.  Use what you've learned so far to insert a couple people, movies, and relationships into the neo4j instance throught he REST service you just deployed (hint:  inspect the controller) 

. Access the application using `curl` to make sure everything is working properly:
+
----
$ curl -i springbox-recommendations-preadherent-werewolf.cfapps.io/recommendations/forMovie/1
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 48
Content-Type: application/json;charset=UTF-8
Date: Tue, 17 Feb 2015 05:46:40 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springbox-recommendations:cloud:63695
X-Cache: MISS from access-gateway.hospitality.swisscom.com
X-Cf-Requestid: 3e9bcafd-e4cc-4047-7355-bad9c84b3b4e

[
    {
        "id": 4,
        "mlId": "2",
        "title": "GoldenEye (1995)"
    }
]
----
