= Lab 15 - Refreshing Configuration with Spring Cloud Bus

[abstract]
--
The http://cloud.spring.io/spring-cloud-bus/[Spring Cloud Bus] links nodes in a distributed system with a lightweight message bus.
We'll use it, combined with a Spring bean scope called `@RefreshScope`, to broadcast configuration changes to our microservices.
The bus will be backed by a running instance of http://www.rabbitmq.com/[RabbitMQ].
--

== Adding the Cloud Bus to the Test Config Client

. Change to the lab directory:
+
----
$ cd $COURSE_HOME/day_02/session_05/lab_15/initial/springbox-config-client
----
+
and import the project (via `pom.xml`) into your IDE of choice.

. In `pom.xml`, add a dependency on `spring-cloud-starter-bus-amqp`:
+
----
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
----

. In the package `io.springbox.configclient`, create the class `Greeter` and paste in the following source code:
+
----
@Component
@RefreshScope
public class Greeter {

    @Value("${greeting}")
    private String greeting;

    public String getGreeting() {
        return greeting;
    }
}
----

. Edit `GreetingController`, replacing the injected value for `greeting` with an injected instance of `Greeter`.
Use that instance to obtain the greeting for the `greeter` request method.
You can paste the following code to accomplish this:
+
----
@RestController
public class GreetingController {

    @Autowired
    Greeter greeter;

    @RequestMapping("/")
    public String greeter() {
        return greeter.getGreeting() + " World!";
    }

}
----

. To run the application now, you'll need a local install of RabbitMQ. You can obtain one for your platform http://www.rabbitmq.com/download.html[here].

. A completed `springbox-config-server` project has been placed in `$COURSE_HOME/day_02/session_05/lab_15/initial/springbox-config-server` for your convenience.
In a different terminal window, change to that directory, rebuild, and run the application:
+
----
$ cd $COURSE_HOME/day_02/session_05/lab_15/initial/springbox-config-server
$ mvn packaage
$ java -jar target/springbox-config-server-0.0.1-SNAPSHOT.jar
----

. Build your new `springbox-config-client`:
+
----
$ mvn package
----

. Run the application:
+
----
$ java -jar target/springbox-config-client-0.0.1-SNAPSHOT.jar
----

. Use `curl` to access the application and make sure that everything is still working as before:
+
----
$ curl -i localhost:8080
HTTP/1.1 200 OK
Content-Length: 12
Content-Type: text/plain;charset=UTF-8
Date: Wed, 18 Feb 2015 21:48:32 GMT
Server: Apache-Coyote/1.1
X-Application-Context: demo

Howdy World!
----

. In a separate terminal window, run another copy of the client on a different port to create a system of apps connected by the bus:
+
----
$ SERVER_PORT=8081 java -jar target/springbox-config-client-0.0.1-SNAPSHOT.jar
----

. Use `curl` to access the second instance running on port `8081`:
+
----
$ curl -i localhost:8081
HTTP/1.1 200 OK
Content-Length: 12
Content-Type: text/plain;charset=UTF-8
Date: Wed, 18 Feb 2015 21:48:32 GMT
Server: Apache-Coyote/1.1
X-Application-Context: demo

Howdy World!
----

. Now, open `demo.yml` from your config-repo and change the greeting:
+
----
greeting: Ohai
----

. Stage, commit, and push your changes:
+
----
git add . && git commit -m "swap greeting" && git push origin master
----

. Using `curl`, test and see that the config server has updated with your new greeting:
+
----
$ curl -i localhost:8888/demo/default
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Wed, 18 Feb 2015 21:58:34 GMT
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
X-Application-Context: bootstrap:8888

{
    "label": "",
    "name": "default",
    "propertySources": [
        {
            "name": "https://github.com/mstine/springbox-config-repo.git/demo.yml",
            "source": {
                "greeting": "Ohai"
            }
        },
        {
            "name": "https://github.com/mstine/springbox-config-repo.git/application.yml",
            "source": {
                "configserver": true
            }
        }
    ]
}
----

. Using `curl`, show that the greeting *has not* refreshed in the client applications:
+
----
$ curl -i localhost:8080
HTTP/1.1 200 OK
Content-Length: 12
Content-Type: text/plain;charset=UTF-8
Date: Wed, 18 Feb 2015 22:00:11 GMT
Server: Apache-Coyote/1.1
X-Application-Context: demo

Howdy World!

$ curl -i localhost:8081
HTTP/1.1 200 OK
Content-Length: 12
Content-Type: text/plain;charset=UTF-8
Date: Wed, 18 Feb 2015 22:00:16 GMT
Server: Apache-Coyote/1.1
X-Application-Context: demo:8081

Howdy World!
----

. Now, `POST` a request to the `/bus/refresh` endpoint to trigger a configuration refresh event:
+
----
$ curl -i -X POST localhost:8080/bus/refresh
HTTP/1.1 200 OK
Content-Length: 0
Date: Wed, 18 Feb 2015 22:01:39 GMT
Server: Apache-Coyote/1.1
X-Application-Context: demo
----

. Using `curl`, show that the greeting *has* now refreshed in the client applications:
+
----
$ curl -i localhost:8080
HTTP/1.1 200 OK
Content-Length: 11
Content-Type: text/plain;charset=UTF-8
Date: Wed, 18 Feb 2015 22:02:31 GMT
Server: Apache-Coyote/1.1
X-Application-Context: demo

Ohai World!

$ curl -i localhost:8081
HTTP/1.1 200 OK
Content-Length: 11
Content-Type: text/plain;charset=UTF-8
Date: Wed, 18 Feb 2015 22:02:35 GMT
Server: Apache-Coyote/1.1
X-Application-Context: demo:8081

Ohai World!
----
